spring.application.name=trade-risk-engine
spring.datasource.url=jdbc:mysql://localhost:3306/trade_risk_db
spring.datasource.username=root
spring.datasource.password=25mcs0031
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# Finnhub API Configuration
finnhub.api.key=d8gmomhr01qlgcukgl0gd8gmomhr01qlgcukgl10
finnhub.api.url=https://finnhub.io/api/v1/quote?symbol=